Support bat as batcat on Debian

diff --git a/src/fzf-select-option-preview b/src/fzf-select-option-preview
--- a/src/fzf-select-option-preview
+++ b/src/fzf-select-option-preview
@@ -89,7 +89,16 @@ parse_args "$@"
 [[ -z $opts ]] && echo "Missing <opts>" && echo "$usage" && exit 1
 [[ -z $index ]] && echo "Missing <index>" && echo "$usage" && exit 1
 
+BAT=bat
+if ! which $BAT; then
+  BAT=batcat
+fi
+if ! which $BAT; then
+  echo "Could not find bat" > /dev/stderr
+  exit 1
+fi
+
 line_number=$(get_line_number "$opts" $index)
 scroll=$(get_scroll_lines $line_number)
 printf '\033[2J'
-bat -f -pp -H $line_number -r $scroll: --language=help
+$BAT -f -pp -H $line_number -r $scroll: --language=help
